#!/usr/bin/python
#
# Implements a module to  insert weather data into the SpOT mySql database

import logging
from collections import deque
import time

  
def weather_record(weather_data):
   # This defines the mapping between a weather record as generated by
   # the Davis interface, and the MySQL table columns
   return {
      'datetime': weather_data['timestr'],
      'it'      : round(weather_data['insideTemperature'],3),
      'irh'     : round(weather_data['insideHumidity'],3),
      'itd'     : round(weather_data['insideDewTemp'],3),
      'ot'      : round(weather_data['outsideTemperature'],3),
      'orh'     : round(weather_data['outsideHumidity'],3),
      'otd'     : round(weather_data['outsideDewTemp'],3),
      'rr'      : round(weather_data['rainRate'],3),
      'inhg'    : round(weather_data['barometer'],5),
      'ws'      : round(weather_data['windSpeed'],3),
      'wsa'     : round(weather_data['windSpeedAvg'],3),
      'wd'      : round(weather_data['windDirection'],3) }

class spot_env_site(object):

   def __init__(self):
      self.log = logging.getLogger('SPOT_ENV_DB')
      self.outbox = deque()

   def put(self,weather_data):
      # This puts it in the queue...
      self.outbox.append(weather_record(weather_data))

   def empty_outbox(self):
      soFarSoGood=True
      while (soFarSoGood and self.outbox):
         wrec=self.outbox.popleft()
         self.log.info(str(wrec))

      return soFarSoGood

   def worker(self,timeInterval,keepWorking):
      #  keeps looking at the queue and empties it to the database
      # keepWorking is an event set in the main thread to allow stoping
      while keepWorking.is_set():
         self.empty_outbox()
         time.sleep(timeInterval)

if __name__ == "__main__":
   logging.basicConfig(level=logging.DEBUG)
   w = spot_env_site()
   wrec={'timestr':'2016-11-29 01:45:00.0','barometer':30.011,'insideTemperature':73.1,'insideHumidity':33,'insideDewTemperature':45.0,'outsideTemperature':44.4,'outsideHumidity':93,'outsideDewTemp':42.5,'windSpeed':0.0,'windSpeedAvg':0.0,'windDirection':132}
